version: "3"

services:
  mc:
    image: ${IMAGE:-itzg/minecraft-server:java17}
    container_name: fabric-susblock-mod-1.19
    environment:
      EULA: "true"
      TYPE: FABRIC
      VERSION: 1.19
      FABRIC_LAUNCHER_VERSION: 0.11.0
      FABRIC_LOADER_VERSION: 0.14.8
      MODPACK: https://github.com/BennyDeeDev/fabric-susblock-mod/releases/download/1.19-1.0.0/fabric-susblock-mod-1.0.0-1.19.zip

    ports:
      - 25565:25565
    volumes:
      - fabric:/data

volumes:
  fabric: {}
